name: my_new_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
 # audio_recorder: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/visuals/images/icons8-speech-to-text-30-1.png
    - assets/visuals/images/icons8-speech-to-text-30-1-krD.png
    - assets/visuals/images/hearing.png
    - assets/research-ia-moodboard-wireframe/images/image-8.png
    - assets/research-ia-moodboard-wireframe/images/image-2.png
    - assets/visuals/images/group-7.png
    - assets/research-ia-moodboard-wireframe/images/image-6.png
    - assets/visuals/images/home.png
    - assets/visuals/images/icons8-speech-to-text-30-1-M45.png
    - assets/research-ia-moodboard-wireframe/images/image-7.png
    - assets/visuals/images/ellipse-3.png
    - assets/visuals/images/ellipse-2.png
    - assets/research-ia-moodboard-wireframe/images/image-1.png
    - assets/visuals/images/frame-2608534.png
    - assets/visuals/images/ellipse-1.png
    - assets/visuals/images/home-u8D.png
    - assets/visuals/images/ellipse-1-LSm.png
    - assets/visuals/images/account-circle.png
    - assets/visuals/images/frame-2608534-vp9.png
    - assets/visuals/images/mic.png
    - assets/visuals/images/right-icons.png
    - assets/visuals/images/component-1.png
    - assets/visuals/images/ellipse-2-QdF.png
    - assets/visuals/images/notification.png
    - assets/visuals/images/hearing-ETB.png
    - assets/visuals/images/moonstars-and-cloud.png
    - assets/research-ia-moodboard-wireframe/images/image-3.png
    - assets/visuals/images/hearing-eKs.png
    - assets/visuals/images/right-icons-Hr1.png
    - assets/visuals/images/home-oa1.png
    - assets/visuals/images/logout.png
    - assets/visuals/images/mask-group.png
    - assets/visuals/images/notification-8rV.png
    - assets/visuals/images/ellipse-4.png
    - assets/visuals/images/account-circle-NSd.png
    - assets/visuals/images/hearing-XqK.png
    - assets/visuals/images/icons8-speech-to-text-30-1-gLq.png
    - assets/visuals/images/account-circle-2L9.png
    - assets/visuals/images/frame-2608534-kHP.png
    - assets/visuals/images/supervised-user-circle.png
    - assets/visuals/images/ellipse-4-NXb.png
    - assets/visuals/images/ellipse-1-Sfs.png
    - assets/visuals/images/moonstars-and-cloud-tHX.png
    - assets/visuals/images/account-circle-xoB.png
    - assets/visuals/images/hearing-wpm.png
    - assets/visuals/images/moonstars-and-cloud-QVP.png
    - assets/visuals/images/right-icons-kJM.png
    - assets/visuals/images/converted-1.png
    - assets/visuals/images/notification-srh.png
    - assets/visuals/images/frame-2608534-uKw.png
    - assets/visuals/images/frame-2608534-jqK.png
    - assets/visuals/images/ellipse-3-SWm.png
    - assets/visuals/images/mask-group-KkD.png
    - assets/visuals/images/ellipse-2-EMP.png
    - assets/visuals/images/home-CB3.png
    - assets/visuals/images/account-circle-2vm.png
    - assets/visuals/images/right-icons-NyF.png
    - assets/visuals/images/ellipse-3-bQd.png
    - assets/visuals/images/hearing-aC1.png
    - assets/visuals/images/home-cRX.png
    - assets/visuals/images/right-icons-YpH.png
    - assets/visuals/images/ellipse-3-KkM.png
    - assets/visuals/images/ellipse-1-M6h.png
    - assets/visuals/images/ellipse-1-bYm.png
    - assets/research-ia-moodboard-wireframe/images/image-10.png
    - assets/visuals/images/ellipse-4-Br9.png
    - assets/research-ia-moodboard-wireframe/images/image-9.png
    - assets/visuals/images/auto-group-ebwp.png
    - assets/visuals/images/home-Ca5.png
    - assets/research-ia-moodboard-wireframe/images/image-5.png
    - assets/research-ia-moodboard-wireframe/images/prototype.png
    - assets/visuals/images/ellipse-3-Zfw.png
    - assets/research-ia-moodboard-wireframe/images/image-12.png
    - assets/visuals/images/icons8-speech-to-text-30-1-Mff.png
    - assets/visuals/images/right-icons-Sad.png
    - assets/research-ia-moodboard-wireframe/images/whatsapp-image-2023-09-08-at-1519-1.png
    - assets/visuals/images/group-12.png
    - assets/visuals/images/icons8-speech-to-text-30-1-qPP.png
    - assets/research-ia-moodboard-wireframe/images/image-4.png
    - assets/research-ia-moodboard-wireframe/images/image-11.png
    - assets/visuals/images/song.png
    - assets/visuals/images/player-volume.png
    - assets/visuals/images/ellipse-2-bg.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
